from pydantic import BaseModel, Field
from typing import Literal, Optional
from app.ai_core.structured_outputs.schemas.rag_response_schema import RAGQueryResponseSchema

class MemoryMessage(BaseModel):
    role: Literal["user", "assistant"] = Field(..., description="The role of the user in the message")
    content: str = Field(..., description="The content of the message")
    timestamp: float = Field(..., description="Unix timestamp of when the message was added to memory")

class ConversationSession(BaseModel):
    user_id: str = Field(..., description="Unique identifier for the user")
    conversation_id: Optional[str] = Field(None, description="The conversation identifier")
    messages: list[MemoryMessage] = Field(default_factory=[], description="List of messages in the conversation session")    

class ConversationRequest(BaseModel):
    user_id: str = Field(..., description="Unique identifier for the user")
    message: str = Field(..., description="The message content")
    conversation_id: Optional[str] = Field(None, description="The conversation identifier")


class ConversationResponse(BaseModel):
    answer: RAGQueryResponseSchema = Field(..., description="The answer generated by the RAG system")
    memory_updated: bool = Field(..., description="Indicates if the memory was updated")
    conversation_id: Optional[str] = Field(None, description="The conversation identifier, if applicable")

