version: "3.9"

name: quantum-mind-ai

services:

  ###########################################################
  # QDRANT VECTOR DATABASE
  ###########################################################
  quantum-mind-qdrant:
    image: qdrant/qdrant:latest

    restart: always

    
    ports:
      - "6333:6333"

    ###########################################################
    # PERSIST VECTOR DATABASE DATA
    ###########################################################

    env_file:
        - ./secrets.env
        
    volumes:
      - quantum-mind-qdrant-data:/qdrant/storage

    ###########################################################
    # INTERNAL NETWORK
    ###########################################################
    networks:
      - quantum-mind-network


  ###########################################################
  # BACKEND (FASTAPI)
  ###########################################################
  quantum-mind-api:

    ###########################################################
    # START QDRANT BEFORE API
    ###########################################################
    depends_on:
      - quantum-mind-qdrant

    image: crawan/quantum-mind-api:latest

    restart: always

    ###########################################################
    # HOST:CONTAINER
    ###########################################################
    ports:
      - "3009:8000"

    ###########################################################
    # ENV VARIABLES
    ###########################################################
    env_file:
      - ./backend/.env

    ###########################################################
    # LIVE DEV MOUNT (OPTIONAL)
    ###########################################################
    volumes:
      - ./backend:/app

    ###########################################################
    # INTERNAL NETWORK
    ###########################################################
    networks:
      - quantum-mind-network


  ###########################################################
  # FRONTEND (ANGULAR)
  ###########################################################
  quantum-mind-client:

    image: crawan/quantum-mind-client:latest

    restart: always

    ports:
      - "3010:80"

    ###########################################################
    # INTERNAL NETWORK
    ###########################################################
    networks:
      - quantum-mind-network


#############################################################
# PERSISTENT VOLUMES
#############################################################
volumes:

  ###########################################################
  # QDRANT STORAGE
  ###########################################################
  quantum-mind-qdrant-data:


#############################################################
# SHARED NETWORK
#############################################################
networks:

  quantum-mind-network:
    driver: bridge