from abc import ABC, abstractmethod

from pydantic import BaseModel
from app.ai_core.structured_outputs.schemas.rag_response_schema import RAGQueryResponseSchema
from backend.app.ai_core.structured_outputs.schemas.ingestion_schema import IngestionResponseSchema


class QueryRequest(BaseModel):
    query: str
    top_k: int = 3
    
class RAGService(ABC):
    @abstractmethod
    def ingest_pdf(self, path: str, source: str) -> IngestionResponseSchema:
        """
        Abstract method to ingest a PDF into the system.

        Parameters
        ----------
        path : str
            The path to the PDF file.
        source : str
            The source of the PDF file.

        Returns
        -------
        IngestionResponseSchema
            The response indicating the outcome of the ingestion process.
        """
        pass
    
    @abstractmethod
    def rag_pipeline(self, payload: QueryRequest) -> RAGQueryResponseSchema:
        """
        Abstract method to execute the entire RAG pipeline, including retrieval and answer generation.

        Parameters
        ----------
        payload : QueryRequest
            The request object containing the query and other parameters.

        Returns
        -------
        RAGQueryResponseSchema
            The final answer generated by the RAG pipeline based on the input query and retrieved information.
        """
        pass
