from pydantic import BaseModel, Field
from typing import Optional

class RAGResponseDto(BaseModel):
    """
    Standard output format for ALL RAG queries.
    This is the contract between LLM and API.
    """

    # Final answer (must be grounded in context)
    answer: str = Field(..., description="The final answer generated by the RAG system, grounded in retrieved context")

    # Simple analogy (optional but helpful for learning queries)
    analogy: Optional[str] = Field(default="", description="Simple analogy to help explain the concept")

    # Model confidence (0.0 → 1.0)
    confidence: float = Field(default=0.0, description="Confidence level of the generated answer (0.0 to 1.0)")

   