# llm_generator.py
# ------------------------------------------------------------------
# FINAL GENERATION STEP OF THE RAG PIPELINE
# ------------------------------------------------------------------
#
# PURPOSE
# -------
# This module transforms retrieved semantic chunks into
# a final human-readable answer using an LLM.
#
# PIPELINE POSITION
# -----------------
# 1. Retriever:
#    Finds semantically relevant chunks.
#
# 2. Reranker:
#    Reorders chunks by true relevance.
#
# 3. Context Builder:
#    Structures chunks for prompting.
#
# 4. THIS MODULE:
#    Generates the final grounded answer.
#
# WHY THIS STEP MATTERS
# ---------------------
# Retrieval alone is NOT enough.
#
# Users do not want:
# - raw chunks
# - messy paragraphs
# - vector search output
#
# They want:
# - direct answers
# - clear explanations
# - educational responses
#
# The LLM acts as the "reasoning + explanation layer"
# on top of retrieval.
# ------------------------------------------------------------------

from typing import List

from groq import Groq

from app.ai_core.llms.groq_llm import groq_llm_call
from app.ai_core.rag.prompt.rag_prompt_builder import RAGPromptBuilder


# ------------------------------------------------------------------
# GENERATE FINAL RAG ANSWER
# ------------------------------------------------------------------

def generate_answer(
    query: str,
    chunks: List[str],
    client: Groq
) -> str:
    """
    Generate the final grounded answer using retrieved context.

    PARAMETERS
    ----------
    query : str
        The user's question.

    chunks : List[str]
        Retrieved and reranked semantic chunks.

        These chunks should already be:
        - relevant
        - cleaned
        - normalized
        - semantically coherent

    client : Groq
        Initialized Groq client used for LLM inference.

    RETURNS
    -------
    str
        Final natural-language answer generated by the LLM.

    GENERATION STRATEGY
    -------------------
    This function:
    1. Builds a structured RAG prompt
    2. Injects retrieved context
    3. Sends the prompt to the LLM
    4. Returns the generated answer

    IMPORTANT
    ---------
    Good RAG generation depends heavily on:
    - retrieval quality
    - chunk quality
    - prompt structure
    - grounding instructions
    """

    # --------------------------------------------------------------
    # SAFETY CHECK:
    # Prevent empty-context hallucinations.
    #
    # If retrieval failed,
    # NEVER ask the LLM to invent an answer.
    # --------------------------------------------------------------
    if not chunks:

        return (
            "I could not find enough relevant information "
            "to answer this question."
        )

    # --------------------------------------------------------------
    # BUILD STRUCTURED RAG PROMPT
    # --------------------------------------------------------------
    #
    # The prompt builder is responsible for:
    # - formatting context
    # - injecting the question
    # - organizing retrieved chunks
    # - improving grounding
    #
    # Good prompt construction is CRITICAL
    # for high-quality RAG systems.
    # --------------------------------------------------------------
    prompt = RAGPromptBuilder.build(
        query=query,
        chunks=chunks
    )

    # --------------------------------------------------------------
    # GENERATE FINAL ANSWER USING THE LLM
    # --------------------------------------------------------------
    #
    # The LLM:
    # - reads the retrieved context
    # - interprets the user's question
    # - synthesizes a grounded answer
    #
    # The system prompt inside groq_llm_call()
    # enforces:
    # - grounding
    # - anti-hallucination
    # - concise explanations
    # --------------------------------------------------------------
    response = groq_llm_call(
        client=client,
        prompt=prompt
    )

    # --------------------------------------------------------------
    # FINAL CLEANUP
    # --------------------------------------------------------------
    #
    # Remove accidental surrounding whitespace
    # before returning the final answer.
    # --------------------------------------------------------------
    return response.strip()