from enum import Enum

class ErrorCode(str, Enum):
    NOT_FOUND = "NOT_FOUND"

    INVALID_TOKEN = "INVALID_TOKEN"

    USER_NOT_FOUND = "USER_NOT_FOUND"

    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"

    PROCESSING_ERROR = "PROCESSING_ERROR"

    USER_PROCESSING_ERROR = "USER_PROCESSING_ERROR"

    CONFLICT = "CONFLICT"
    
    # ============================================================
    # AUTHENTICATION
    # ============================================================

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"

    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"

    AUTHENTICATION_PROCESSING_ERROR = "AUTHENTICATION_PROCESSING_ERROR"


    # ============================================================
    # PROFILE
    # ============================================================
    PROFILE_ALREADY_EXISTS = 'PROFILE_ALREADY_EXISTS'
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_PROCESSING_ERROR = "PROFILE_PROCESSING_ERROR"


    # =======
    # SECURITY
    # =======
    USER_SESSION_NOT_FOUND = "USER_SESSION_NOT_FOUND"
    USER_SESSION_PROCESSING_ERROR = "USER_SESSION_PROCESSING_ERROR"