from enum import Enum

class ErrorCode(str, Enum):
    NOT_FOUND = "NOT_FOUND"
    INVALID_TOKEN = "INVALID_TOKEN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"