from abc import ABC, abstractmethod

from pydantic import BaseModel
from app.v1.modules.rag.dto.rag_finale_response_dto import RAGQueryFinaleResponseDto
from app.v1.modules.rag.dto.conversation_dto import StreamingResponseDto

class QueryRequest(BaseModel):
    query: str
    top_k: int = 3
    
class RAGService(ABC):
    @abstractmethod
    async def rag_stream_pipeline(self, payload: QueryRequest) -> StreamingResponseDto:
        pass
        
    @abstractmethod
    def rag_pipeline(self, payload: QueryRequest) -> RAGQueryFinaleResponseDto:
        """
        Abstract method to execute the entire RAG pipeline, including retrieval and answer generation.

        Parameters
        ----------
        payload : QueryRequest
            The request object containing the query and other parameters.

        Returns
        -------
        RAGQueryResponseSchema
            The final answer generated by the RAG pipeline based on the input query and retrieved information.
        """
        pass
