from pydantic import BaseModel, Field
from typing import List, Optional


class RAGResponseSchema(BaseModel):
    """
    Standard output format for ALL RAG queries.
    This is the contract between LLM and API.
    """

    # Final answer (must be grounded in context)
    answer: str = Field(..., description="The final answer generated by the RAG system, grounded in retrieved context")

    # Key extracted facts (no formatting, no markdown)
    key_points: List[str] = Field(default_factory=[], description="List of key points extracted from the retrieved context")

    # Step-by-step explanation (only if useful)
    step_by_step: List[str] = Field(default_factory=[], description="A step-by-step explanation of how the answer was derived, if applicable")    

    # Simple analogy (optional but helpful for learning queries)
    analogy: Optional[str] = Field(default="", description="Simple analogy to help explain the concept")

    # Model confidence (0.0 → 1.0)
    confidence: float = Field(default=0.0, description="Confidence level of the generated answer (0.0 to 1.0)")

    # Optional: traceability to chunks
    sources: List[str] = Field(default_factory=[], description="List of sources or chunk identifiers that support the answer")