from typing import (List, Generator,  Any)
import json
import time
from groq import Groq
from app.v1.modules.rag.dto.rag_response_dto import RAGResponseDto
from app.ai_core.llms.groq_llm import (groq_llm_call, groq_llm_call_streaming)
from app.v1.modules.rag.prompt.rag_prompt_builder import RAGPromptBuilder


def generate_streaming_answer(
    query: str,
    chunks: List[str],
    client: Groq
) -> Generator[str, None, None]:
    """
    Generate the final grounded answer using retrieved context.

    PARAMETERS
    ----------
    query : str
        The user's question.

    chunks : List[str]
        Retrieved and reranked semantic chunks.

        These chunks should already be:
        - relevant
        - cleaned
        - normalized
        - semantically coherent

    client : Groq
        Initialized Groq client used for LLM inference.

    RETURNS
    -------
    RAGResponseSchema
        Final structured response generated by the LLM.

    GENERATION STRATEGY
    -------------------
    This function:
    1. Builds a structured RAG prompt
    2. Injects retrieved context
    3. Sends the prompt to the LLM
    4. Returns the generated answer

    IMPORTANT
    ---------
    Good RAG generation depends heavily on:
    - retrieval quality
    - chunk quality
    - prompt structure
    - grounding instructions
    """

    # --------------------------------------------------------------
    # SAFETY CHECK:
    # Prevent empty-context hallucinations.
    #
    # If retrieval failed,
    # NEVER ask the LLM to invent an answer.
    # --------------------------------------------------------------
    if not chunks:
        message =  "I could not find reliable information, to answer this question."
        yield f"data: {json.dumps(message)}\n\n"
        return

    # --------------------------------------------------------------
    # BUILD STRUCTURED RAG PROMPT
    # --------------------------------------------------------------
    prompt = RAGPromptBuilder.build_stream(
        query=query,
        chunks=chunks
    )

    # --------------------------------------------------------------
    # GENERATE FINAL ANSWER USING THE LLM
    # --------------------------------------------------------------
    response: Generator[str, None, None] = groq_llm_call_streaming(
        client=client,
        prompt=prompt
    )
    

    # Parse raw JSON string into dict
    for chunk in response:
        yield chunk



# ------------------------------------------------------------------
# FINAL GENERATION STEP OF THE RAG PIPELINE
# ------------------------------------------------------------------
#
# PURPOSE
# -------
# This module transforms retrieved semantic chunks into
# a final human-readable answer using an LLM.
#
# PIPELINE POSITION
# -----------------
# 1. Retriever:
#    Finds semantically relevant chunks.
#
# 2. Reranker:
#    Reorders chunks by true relevance.
#
# 3. Context Builder:
#    Structures chunks for prompting.
#
# 4. THIS MODULE:
#    Generates the final grounded answer.
#
# WHY THIS STEP MATTERS
# ---------------------
# Retrieval alone is NOT enough.
#
# Users do not want:
# - raw chunks
# - messy paragraphs
# - vector search output
#
# They want:
# - direct answers
# - clear explanations
# - educational responses
#
# The LLM acts as the "reasoning + explanation layer"
# on top of retrieval.
# ------------------------------------------------------------------
# ------------------------------------------------------------------
# GENERATE FINAL RAG ANSWER
# ------------------------------------------------------------------
def generate_answer(
    query: str,
    chunks: List[str],
    client: Groq
) -> RAGResponseDto:
    """
    Generate the final grounded answer using retrieved context.

    PARAMETERS
    ----------
    query : str
        The user's question.

    chunks : List[str]
        Retrieved and reranked semantic chunks.

        These chunks should already be:
        - relevant
        - cleaned
        - normalized
        - semantically coherent

    client : Groq
        Initialized Groq client used for LLM inference.

    RETURNS
    -------
    RAGResponseSchema
        Final structured response generated by the LLM.

    GENERATION STRATEGY
    -------------------
    This function:
    1. Builds a structured RAG prompt
    2. Injects retrieved context
    3. Sends the prompt to the LLM
    4. Returns the generated answer

    IMPORTANT
    ---------
    Good RAG generation depends heavily on:
    - retrieval quality
    - chunk quality
    - prompt structure
    - grounding instructions
    """

    # --------------------------------------------------------------
    # SAFETY CHECK:
    # Prevent empty-context hallucinations.
    #
    # If retrieval failed,
    # NEVER ask the LLM to invent an answer.
    # --------------------------------------------------------------
    if not chunks:
        return RAGResponseSchema(
            answer="I don't know based on the provided context",
            analogy="",
            confidence=0.0,
            sources=[]
        )

    # --------------------------------------------------------------
    # BUILD STRUCTURED RAG PROMPT
    # --------------------------------------------------------------
    #
    # The prompt builder is responsible for:
    # - formatting context
    # - injecting the question
    # - organizing retrieved chunks
    # - improving grounding
    #
    # Good prompt construction is CRITICAL
    # for high-quality RAG systems.
    # --------------------------------------------------------------
    prompt = RAGPromptBuilder.build(
        query=query,
        chunks=chunks
    )

    # --------------------------------------------------------------
    # GENERATE FINAL ANSWER USING THE LLM
    # --------------------------------------------------------------
    #
    # The LLM:
    # - reads the retrieved context
    # - interprets the user's question
    # - synthesizes a grounded answer
    #
    # The system prompt inside groq_llm_call()
    # enforces:
    # - grounding
    # - anti-hallucination
    # - concise explanations
    # --------------------------------------------------------------
    general_start_anser = time.perf_counter()

    response = groq_llm_call(
        client=client,
        prompt=prompt
    )
    print("general_start_anser_timer___:\n",  time.perf_counter() - general_start_anser)

    # Parse raw JSON string into dict
    data = json.loads(response)
    # --------------------------------------------------------------
    # FINAL CLEANUP
    # --------------------------------------------------------------
    #
    # Remove accidental surrounding whitespace
    # before returning the final answer.
    # --------------------------------------------------------------

    return  RAGResponseSchema.model_validate(data)
